name: docker-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./ConsoleApplication1

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: run-home

    steps:
    - uses: actions/checkout@v3
    
    - name: User
      run: echo $env:UserName

    - name: Get latest image
      run: docker pull registry.matrixlt.local/msvs-2022

    - name: Compile in docker
      run: docker run --rm -v ${{env.GITHUB_WORKSPACE}}:C:\build -w C:\build registry.matrixlt.local/msvs-2022 msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Run exe
      run: ${{env.SOLUTION_FILE_PATH}}/x64/Release/ConsoleApplication1.exe
